[project]
name = "gcp-adk-mcp-pricing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp==2.5.1",
    "google-adk>=1.21.0",
    "pydantic==2.11.7",
]
